/**
 * Stable error codes for ContextForge.
 * These codes remain stable across V1 releases.
 */
export const ErrorCodes = {
  VALIDATION_ERROR: 'CF_VALIDATION_ERROR',
  CONFIGURATION_ERROR: 'CF_CONFIGURATION_ERROR',
  PROJECT_NOT_FOUND: 'CF_PROJECT_NOT_FOUND',
  PATH_OUTSIDE_WORKSPACE: 'CF_PATH_OUTSIDE_WORKSPACE',
  SCAN_ERROR: 'CF_SCAN_ERROR',
  FILE_READ_ERROR: 'CF_FILE_READ_ERROR',
  UNSUPPORTED_ENCODING: 'CF_UNSUPPORTED_ENCODING',
  SECURITY_VIOLATION: 'CF_SECURITY_VIOLATION',
  PACKING_ERROR: 'CF_PACKING_ERROR',
  GENERATION_ERROR: 'CF_GENERATION_ERROR',
  OUTPUT_VALIDATION_ERROR: 'CF_OUTPUT_VALIDATION_ERROR',
  PREVIEW_MISMATCH: 'CF_PREVIEW_MISMATCH',
  CANCELLATION_ERROR: 'CF_CANCELLATION_ERROR',
  LAST_PACK_NOT_FOUND: 'CF_LAST_PACK_NOT_FOUND',
  INVALID_STATE_TRANSITION: 'CF_INVALID_STATE_TRANSITION',
  INVALID_AGGREGATE: 'CF_INVALID_AGGREGATE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
