/**
 * Default structural exclusions applied before any ignore rules.
 * These directories are never scanned for candidate files.
 *
 * Security: exclusions are case-sensitive and must match the default
 * directory names exactly as generated by common toolchains.
 */
export const DEFAULT_EXCLUSIONS = [
  '.git',
  '.contextforge',
  'node_modules',
  'dist',
  'build',
  'coverage',
  '.next',
  '.nuxt',
  '.cache',
  'tmp',
  'temp',
  'vendor',
  'out',
  '.turbo',
] as const;

/**
 * Checks if a given directory name (single segment) should be excluded
 * by default structural rules.
 */
export function isDefaultExcludedDir(segment: string): boolean {
  return (DEFAULT_EXCLUSIONS as readonly string[]).includes(segment);
}
